### ISSUE TITLE
Missing comma in CSS? Numbers highlight

### ISSUE THREAD

**Issue by mildsunrise** [LeaVerou/dabblet#208]
[At `style.css`](https://github.com/LeaVerou/dabblet/blob/master/style/style.css#L463):

``` css
.property,
.tag,
.boolean,
.number
.popup > .content a {
    color: #905;
}
```

I guess a comma is necessary after `.number`.
